Agrega botón en mapa y al dar click imprime mensaje en consola
IslasGECI/natividad_rat_control pull request #1
Opened 2019-06-26 19:43 UTC by fiorellam

Añadí un botón sobre el mapa de google y cuando se le da click se puede ver un mensaje en consola.

2019-06-26 19:49 UTC, efren-cabrera requested changes

2019-06-26 19:49 UTC, efren-cabrera commented on web/static/css/main.css
> +    z-index: 1000001;
¿por qué pusiste este valor a z-index?

2019-06-26 19:49 UTC, efren-cabrera commented on web/static/js/main.js
> +function consoleMessage(){
Por favor agrega esta función dentro del cuerpo de la función que se ejecuta cuando carga por completo la página. Así evitamos contaminar el entorno antes de que se cargue la página (En realidad es porque a mí me gusta más como se ve así).

2019-06-27 16:48 UTC, fiorellam commented on web/static/css/main.css
> +    z-index: 1000001;
Me había estado guiando de una de las propiedades de los controles del mapa de google, pero ya me di cuenta que no es necesario el z-index

2019-06-27 17:10 UTC, fiorellam commented on web/static/js/main.js
> +function consoleMessage(){
Listo, ya quedó

2019-06-27 18:54 UTC, efren-cabrera approved these changes
Ahora si me parecen bien los cambios, lo agregaré a la rama _develop_ como ejemplo de como agregar un botón, pero después lo quitaremos ya que esto solo es un ejemplo

2019-06-27 18:55 UTC, merged